name: docker build

on:
  push:
    branches: [ main ]

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dockerfile build
        run: |
          docker build \
          -t ${{ secrets.ACR_URL }}/yk-base/ubuntu-docker:latest \
          -t ${{ secrets.ACR_URL }}/yk-base/ubuntu-docker:${{ github.sha }} \
          - << EOF
          # 使用基础镜像为Ubuntu
          FROM ubuntu
          
          # 设置时区为上海
          ENV TZ=Asia/Shanghai
          
          # 设置时区为上海，安装必要的工具，并清理不需要的软件包
          RUN apt-get update \
              && apt-get install -y vim curl wget docker.io \
              && apt-get autoremove -y \
              && apt-get clean \
              && rm -rf /var/lib/apt/lists/* \
              && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
              && echo $TZ > /etc/timezone
          
          # 启动一个bash shell
          CMD ["/bin/bash"] 
          EOF
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          region-id: cn-shanghai
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Docker Push to ACR
        run: |
          docker images | grep -E '${{ secrets.ACR_URL }}' | awk '{print "docker push "$1":"$2}' | sh
